---
title: "Final Project_1"
author: "Wenyi Wang"
date: "2025-12-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(lubridate)
library(readr)
library(httr)
library(jsonlite)
library(quantmod)
library(fredr)
```

```{r}
key <- readLines("~/Desktop/Fall 2025/SURVMETH 727/fredapi.txt")
fredr_set_key(key)
```

```{r}
start_date <- as.Date("2015-01-01")
end_date   <- as.Date("2024-12-31")
```


```{r}
unrate <- fredr(series_id = "UNRATE",
                observation_start = start_date,
                observation_end   = end_date) %>%
  transmute(date = as.Date(date),
            unrate = value)

cpi <- fredr(series_id = "CPIAUCSL",
             observation_start = start_date,
             observation_end   = end_date) %>%
  transmute(date = as.Date(date),
            cpi = value)

sent <- fredr(series_id = "UMCSENT",
              observation_start = start_date,
              observation_end   = end_date) %>%
  transmute(date = as.Date(date),
            sentiment = value)
```

```{r}
macro <- unrate %>%
  left_join(cpi,  by = "date") %>%
  left_join(sent, by = "date") %>%
  arrange(date) %>%
  mutate(
    unrate_lag1 = lag(unrate, 1),
    covid_dummy = ifelse(date >= as.Date("2020-03-01"), 1, 0)
  )
```

```{r}
get_wiki_views <- function(article){
  url <- paste0(
    "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/",
    "en.wikipedia.org/all-access/all-agents/",
    URLencode(article), "/monthly/2015010100/2024123100"
  )
  
  res <- GET(url)
  stop_for_status(res)
  
  dat <- fromJSON(content(res, "text", encoding = "UTF-8"))
  
  df <- dat$items %>%
    transmute(
      date = as.Date(paste0(substr(timestamp, 1, 6), "01"), format="%Y%m%d"),
      wiki_unemp = views
    )
  return(df)
}

wiki_unemp <- get_wiki_views("Unemployment")
```

```{r}
getSymbols("^VIX", src = "yahoo")

vix_daily <- data.frame(
  date = index(VIX),
  VIX  = as.numeric(Cl(VIX))
)

vix_monthly <- vix_daily %>%
  mutate(date = as.Date(format(date, "%Y-%m-01"))) %>%
  group_by(date) %>%
  summarise(VIX = mean(VIX, na.rm = TRUE), .groups = "drop")
```

```{r}
macro_extended <- macro %>%
  left_join(wiki_unemp,  by = "date") %>%
  left_join(vix_monthly, by = "date") %>%
  mutate(
    wiki_unemp_z = as.numeric(scale(wiki_unemp)),
    VIX_z        = as.numeric(scale(VIX))
  ) %>%
  arrange(date)

```

```{r}
write_csv(macro_extended, "macro_extended.csv")
```

